version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: interview_prep_db
    environment:
      POSTGRES_DB: interview_prep
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d interview_prep']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
